# Generated by Django 5.1.1 on 2024-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongprofile',
            name='area_atuacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='email_contato',
            field=models.EmailField(default='email@exemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='responsavel_legal',
            field=models.CharField(default='Não informado', max_length=255),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='areas_interesse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='disponibilidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='email_alternativo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='experiencia_previa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='motivacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='profissao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='referencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='nome_da_ong',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
