# Generated by Django 5.0.6 on 2024-09-19 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_ongprofile_area_atuacao_ongprofile_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongprofile',
            name='area_atuacao',
            field=models.CharField(default='Área de atuação não informada', max_length=255),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='cnpj',
            field=models.CharField(default='00.000.000/0000-00', max_length=18),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='descricao',
            field=models.TextField(default='Descrição não informada'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='documentos',
            field=models.FileField(default='documentos/default.pdf', upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='endereco',
            field=models.CharField(default='Endereço não informado', max_length=255),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='logotipo',
            field=models.ImageField(default='logos/default_logo.png', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='nome_da_ong',
            field=models.CharField(default='Nome da ONG', max_length=255),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='responsavel_legal',
            field=models.CharField(default='Responsável não informado', max_length=255),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='site',
            field=models.URLField(default='https://www.exemplo.com'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='telefone',
            field=models.CharField(default='(00) 0000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='areas_interesse',
            field=models.CharField(default='Áreas de interesse não informadas', max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='disponibilidade',
            field=models.CharField(default='Disponibilidade não informada', max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='email_alternativo',
            field=models.EmailField(default='email@exemplo.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='endereco',
            field=models.CharField(default='Endereço não informado', max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='experiencia_previa',
            field=models.TextField(default='Experiência prévia não informada'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='foto_perfil',
            field=models.ImageField(default='fotos_perfil/default_foto.png', upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='genero',
            field=models.CharField(default='Não informado', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='habilidades',
            field=models.TextField(default='Habilidades não informadas'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='motivacao',
            field=models.TextField(default='Motivação não informada'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='nome_completo',
            field=models.CharField(default='Nome Completo', max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='profissao',
            field=models.CharField(default='Profissão não informada', max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='referencias',
            field=models.TextField(default='Referências não informadas'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='telefone',
            field=models.CharField(default='(00) 0000-0000', max_length=20),
        ),
    ]
